_G.brewxp = true
while _G.brewxp do
    -- Players.Ruichaochen.PlayerGui.ScreenGui.ClientScript:50 function FireServer
-- Players.Ruichaochen.PlayerGui.ScreenGui.ClientScript.Modules.GuiService:9788
-- Script was generated by Filtershark
local tbl_main = 
{
      "BrewPotion", 
      2
}
game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer(unpack(tbl_main))
wait(0.01)
end