_G.brewmaxlvl = true
while _G.brewmaxlvl do
    -- Players.Ruichaochen.PlayerGui.ScreenGui.ClientScript:50 function FireServer
-- Players.Ruichaochen.PlayerGui.ScreenGui.ClientScript.Modules.GuiService:9788
-- Script was generated by Filtershark
local tbl_main = 
{
      "BrewPotion", 
      4
}
game:GetService("ReplicatedStorage").NetworkRemoteEvent:FireServer(unpack(tbl_main))
wait(180)
end